{% set name = "wagtail-cache" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coderedcorp/wagtail-cache/archive/v{{ version }}.tar.gz
  sha256: 3a5c865408bae67d80af2d52f7297bc186c0671bbad12abd21bb1111cb79c633

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - wagtail >=3.0,<7

test:
  imports:
    - wagtailcache
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/coderedcorp/wagtail-cache
  summary: A simple page cache for Wagtail based on the Django cache middleware.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
